version: '3.9'
services:
    db:
        image: postgres
        restart: always
        env_file: .env-db
        ports: 
            - "5433:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    redis:
        image: redis
        restart: always
        ports: 
            - "6380:6379"
        volumes:
            - redis_data:/data
        entrypoint: redis-server --appendonly yes

volumes: 
    redis_data:
    postgres_data: