version: '3.9'
services:
    db:
        image: postgres
        restart: always
        env_file: .env
        expose: 
            - 5432
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    redis:
        image: redis
        restart: always
        expose: 
            - 6379
        volumes:
            - redis_data:/data
        entrypoint: redis-server --appendonly yes
    ironman:
        build:
            context: ./py-app
            dockerfile: Dockerfile.py-app
        environment: 
            - PORT=8081
        volumes: 
            - ./data:/app/data
            - mydatavol:/app/mydatavol
        expose: 
            - 8081
        depends_on: 
            - db
    falcon:
        build:
            context: ./express-app
            dockerfile: Dockerfile.express-app
        environment: 
            - PORT=8082
        volumes: 
            - ./data:/app/data
        expose: 
            - 8082
    zemo:
        build:
            context: ./php-app
            dockerfile: Dockerfile.php-app
        environment:
            - PORT=8083
        expose: 
            - 8083
    batman:
        build:
            context: ./go-app
            dockerfile: Dockerfile.go-app
        environment:
            - PORT=8084
        expose: 
            - 8084
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx
        ports:
            - 8080:80
        volumes: 
            - ./data:/www/static/
        depends_on: 
            - ironman
            - falcon
            - zemo
            - batman

volumes: 
    redis_data:
    postgres_data:
    data:
        external: true
    mydatavol: